### PR TITLE
Support for detecting free port in range

### PR DESCRIPTION
**Pull request by marcosnz**
Port property can now be a range such as 8000-8100. This allows for a
port to be in use and to select another one (one use case is when more
than one agent on same server).

Please note that I am not a Java developer and this was written in a text editor and not tested :(
Sorry!

### CODE REVIEW

**Comment by EKibort** [comment]
Thank you! 
Did you built and test this code?

**Comment by marcosnz** [comment]
No, I'm sorry. I am a .Net developer and don't have a Java compiler.
If you compile for me I will be happy to test the Jar...?

**Comment by marcosnz** [comment]
I managed to work out how to compile - still not tested (haven't worked out how to produce correct jar) but at least fixed the compile errors

**Comment by EKibort** [comment]
Ok. Thank you. I'll try to check it at weekend.

**Comment by EKibort** [comment]
Thank you.
Be careful - if you tries to specify range with busy ports plugin stucks. Would be better to generate random list with ports and use for loop by such list instead of while loop.

**Pull request merged**
